# https://gist.github.com/jcavat/2ed51c6371b9b488d6a940ba1049189b
# https://hub.docker.com/_/mysql

version: '3.7'

services:


  #  █████  ██████   █████   ██████ ██   ██ ███████ 
  # ██   ██ ██   ██ ██   ██ ██      ██   ██ ██      
  # ███████ ██████  ███████ ██      ███████ █████   
  # ██   ██ ██      ██   ██ ██      ██   ██ ██      
  # ██   ██ ██      ██   ██  ██████ ██   ██ ███████ 

  # Made from Dockerfile in local directory
  # Why? Because we have to install plugins

  server-a-0:
    container_name: server-a-0
    hostname: server-a-0
    image: blue-green-test/apache-php
    ports:
      - "8080:80"
    volumes:
      - ./www-server-a:/var/www/html/:ro
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.1.0

  server-a-1:
    container_name: server-a-1
    hostname: server-a-1
    image: blue-green-test/apache-php
    ports:
      - "8081:80"
    volumes:
      - ./www-server-a:/var/www/html/:ro
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.1.1

  server-a-2:
    container_name: server-a-2
    hostname: server-a-2
    image: blue-green-test/apache-php
    ports:
      - "8082:80"
    volumes:
      - ./www-server-a:/var/www/html/:ro
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.1.2

  server-b-0:
    container_name: server-b-0
    hostname: server-b-0
    image: blue-green-test/apache-php
    ports:
      - "8090:80"
    volumes:
      - ./www-server-b:/var/www/html/:ro
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.2.0


  server-b-1:
    container_name: server-b-1
    hostname: server-b-1
    image: blue-green-test/apache-php
    ports:
      - "8091:80"
    volumes:
      - ./www-server-b:/var/www/html/:ro
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.2.1

  server-b-2:
    container_name: server-b-2
    hostname: server-b-2
    image: blue-green-test/apache-php
    ports:
      - "8092:80"
    volumes:
      - ./www-server-b:/var/www/html/:ro
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.2.2

# ██████  ███████ ██████  ██ ███████ 
# ██   ██ ██      ██   ██ ██ ██      
# ██████  █████   ██   ██ ██ ███████ 
# ██   ██ ██      ██   ██ ██      ██ 
# ██   ██ ███████ ██████  ██ ███████ 

  redis-a:
    container_name: redis-a
    hostname: redis-a
    image: redis
    ports:
    - "16379:6379"
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.3.1    

  redis-b:
    container_name: redis-b
    hostname: redis-b
    image: redis
    ports:
    - "26379:6379"
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.3.2    

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=redis-a:redis-a:6379,redis-b:redis-b:6379
    - URL_PREFIX=/redis
    # Exposed through nginx
    # ports:
    # - "8081:8081"
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.3.100

  # ███    ██  ██████  ██ ███    ██ ██   ██ 
  # ████   ██ ██       ██ ████   ██  ██ ██  
  # ██ ██  ██ ██   ███ ██ ██ ██  ██   ███   
  # ██  ██ ██ ██    ██ ██ ██  ██ ██  ██ ██  
  # ██   ████  ██████  ██ ██   ████ ██   ██ 

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    volumes:
    # - ./templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/blue-green:/etc/nginx/blue-green:ro
      - ./nginx/logs:/var/log/nginx
    ports:
    - "80:80"
    - "6379:6379"
    # environment:
    # - NGINX_HOST=foobar.com
    # - NGINX_PORT=80
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.0.2

networks:
  blue-green-network:
    name: blue-green-network
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1