# https://gist.github.com/jcavat/2ed51c6371b9b488d6a940ba1049189b
# https://hub.docker.com/_/mysql

version: '3.7'

services:


  #  █████  ██████   █████   ██████ ██   ██ ███████ 
  # ██   ██ ██   ██ ██   ██ ██      ██   ██ ██      
  # ███████ ██████  ███████ ██      ███████ █████   
  # ██   ██ ██      ██   ██ ██      ██   ██ ██      
  # ██   ██ ██      ██   ██  ██████ ██   ██ ███████ 

  # Made from Dockerfile in local directory
  # Why? Because we have to install plugins

  server-a-0:
    container_name: server-a-0
    image: blue-green-test/apache-php
    ports:
      - "8080:80"
    volumes:
      - ./www-server-a:/var/www/html/:ro
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.1.0

  server-a-1:
    container_name: server-a-1
    image: blue-green-test/apache-php
    ports:
      - "8080:80"
    volumes:
      - ./www-server-a:/var/www/html/:ro
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.1.1

  server-a-2:
    container_name: server-a-2
    image: blue-green-test/apache-php
    ports:
      - "8080:80"
    volumes:
      - ./www-server-a:/var/www/html/:ro
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.1.2

  server-b-0:
    container_name: server-b-0
    image: blue-green-test/apache-php
    ports:
      - "8081:80"
    volumes:
      - ./www-server-b:/var/www/html/:ro
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.2.0


  server-b-1:
    container_name: server-b-1
    image: blue-green-test/apache-php
    ports:
      - "8081:80"
    volumes:
      - ./www-server-b:/var/www/html/:ro
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.2.1

  server-b-2:
    container_name: server-b-2
    image: blue-green-test/apache-php
    ports:
      - "8081:80"
    volumes:
      - ./www-server-b:/var/www/html/:ro
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.2.2


  # ███    ██  ██████  ██ ███    ██ ██   ██ 
  # ████   ██ ██       ██ ████   ██  ██ ██  
  # ██ ██  ██ ██   ███ ██ ██ ██  ██   ███   
  # ██  ██ ██ ██    ██ ██ ██  ██ ██  ██ ██  
  # ██   ████  ██████  ██ ██   ████ ██   ██ 

  nginx:
    container_name: nginx
    image: nginx
    volumes:
    # - ./templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/blue-green:/etc/nginx/blue-green:ro
    ports:
    - "80:80"
    # environment:
    # - NGINX_HOST=foobar.com
    # - NGINX_PORT=80
    restart: unless-stopped
    networks:
      blue-green-network:
        ipv4_address: 172.18.0.2

networks:
  blue-green-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1