# https://gist.github.com/jcavat/2ed51c6371b9b488d6a940ba1049189b
# https://hub.docker.com/_/mysql

version: '3.7'

services:


  #  █████  ██████   █████   ██████ ██   ██ ███████ 
  # ██   ██ ██   ██ ██   ██ ██      ██   ██ ██      
  # ███████ ██████  ███████ ██      ███████ █████   
  # ██   ██ ██      ██   ██ ██      ██   ██ ██      
  # ██   ██ ██      ██   ██  ██████ ██   ██ ███████ 

  # Made from Dockerfile in local directory
  # Why? Because we have to install plugins

  server-a:
    container_name: server-a
    image: blue-green-test/apache-php
    ports:
      - "8080:80"
    volumes:
      - ./www-server-a:/var/www/html/
    restart: unless-stopped


  server-b:
    container_name: server-b
    image: blue-green-test/apache-php
    ports:
      - "8081:80"
    volumes:
      - ./www-server-b:/var/www/html/
    restart: unless-stopped

  # ███    ██  ██████  ██ ███    ██ ██   ██ 
  # ████   ██ ██       ██ ████   ██  ██ ██  
  # ██ ██  ██ ██   ███ ██ ██ ██  ██   ███   
  # ██  ██ ██ ██    ██ ██ ██  ██ ██  ██ ██  
  # ██   ████  ██████  ██ ██   ████ ██   ██ 

  nginx:
    container_name: nginx
    image: nginx
    # volumes:
    # - ./templates:/etc/nginx/templates
    ports:
    - "80:80"
    # environment:
    # - NGINX_HOST=foobar.com
    # - NGINX_PORT=80
    restart: unless-stopped


